# Generated by Django 3.0.3 on 2020-04-07 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200407_0946'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
